from pathlib import Path
R=Path('/root/dism125m-v4/dism_v3/python/flash_dism')
def edit(n,a,b,count=1):
 p=R/n;s=p.read_text();assert s.count(a)==count,(n,a,s.count(a));p.write_text(s.replace(a,b))
edit('forward.py','_lse_preabsorbed=False):','_lse_preabsorbed=False,gate_delta=None):')
edit('forward.py','(q,k,sq,sk,v,q_lse,k_lse,idx_q,idx_k,direction,hard,rtau),','(q,k,sq,sk,v,q_lse,k_lse,idx_q,idx_k,direction,hard,rtau)+(() if gate_delta is None else (gate_delta,)),')
edit('backward.py','tau,ctas,absorbed):','tau,ctas,absorbed,gate_delta):')
edit('backward.py','ctas=ctas,save_state=True,_lse_preabsorbed=absorbed)','ctas=ctas,save_state=True,_lse_preabsorbed=absorbed,gate_delta=gate_delta)')
edit('backward.py','        ctx.n=q.shape[1]','        ctx.operand_count=len(state["operands"])\n        ctx.n=q.shape[1]')
edit('backward.py','state=dict(operands=saved[:13],vertical=saved[13],output=saved[14],\n                   lse2=saved[15],n=ctx.n)','n=ctx.operand_count\n        state=dict(operands=saved[:n],vertical=saved[n],output=saved[n+1],\n                   lse2=saved[n+2],n=ctx.n)')
edit('backward.py',"None,None,None,None,g['rtau'],None,None)","None,None,None,None,g['rtau'],None,None,g.get('gate_delta'))")
edit('backward.py','ctas=0,_lse_preabsorbed=False):','ctas=0,_lse_preabsorbed=False,gate_delta=None):')
edit('backward.py','hard,rtau,ctas,_lse_preabsorbed)','hard,rtau,ctas,_lse_preabsorbed,gate_delta)')
edit('voc.py','direction,hard,ctas=0):','direction,hard,ctas=0,gate_delta=None):')
edit('voc.py','rtau,ctas=ctas,_lse_preabsorbed=True)','rtau,ctas=ctas,_lse_preabsorbed=True,gate_delta=gate_delta)')
edit('varlen.py','fp32_output=False,_lse_preabsorbed=False):','fp32_output=False,_lse_preabsorbed=False,gate_delta=None):')
edit('varlen.py','(q,k,sq,sk,v,q_lse,k_lse,idx_q,idx_k,direction,hard,rtau),','(q,k,sq,sk,v,q_lse,k_lse,idx_q,idx_k,direction,hard,rtau)+(() if gate_delta is None else (gate_delta,)),')
edit('varlen.py','tau,layout,absorbed):','tau,layout,absorbed,gate_delta):')
edit('varlen.py','layout=layout,save_state=True,_lse_preabsorbed=absorbed)','layout=layout,save_state=True,_lse_preabsorbed=absorbed,gate_delta=gate_delta)')
edit('varlen.py','        ctx.layout=layout','        ctx.operand_count=len(state["operands"])\n        ctx.layout=layout')
edit('varlen.py','state=dict(layout=ctx.layout,operands=saved[:13],vertical=saved[13],\n                   output=saved[14],normalizer=saved[15])','n=ctx.operand_count\n        state=dict(layout=ctx.layout,operands=saved[:n],vertical=saved[n],\n                   output=saved[n+1],normalizer=saved[n+2])')
edit('varlen.py',"None,None,None,None,g['rtau'],None,None)","None,None,None,None,g['rtau'],None,None,g.get('gate_delta'))")
edit('varlen.py','layout=None,_lse_preabsorbed=False):','layout=None,_lse_preabsorbed=False,gate_delta=None):')
edit('varlen.py','hard,rtau,layout,_lse_preabsorbed)','hard,rtau,layout,_lse_preabsorbed,gate_delta)')
edit('varlen.py','*,direction,hard,layout=None):','*,direction,hard,layout=None,gate_delta=None):')
edit('varlen.py','direction,hard,rtau,layout=layout)','direction,hard,rtau,layout=layout,gate_delta=gate_delta)')
edit('varlen.py','direction,hard,rtau,layout=layout,_lse_preabsorbed=True)','direction,hard,rtau,layout=layout,_lse_preabsorbed=True,gate_delta=gate_delta)')
# Top level public dispatch
edit('__init__.py','def dism_core(*args, cu_seqlens=None, layout=None, ctas=0):','def dism_core(*args, cu_seqlens=None, layout=None, ctas=0, gate_delta=None):')
edit('__init__.py','return dism_core_varlen(*args,cu_seqlens=cu_seqlens,layout=layout)','return dism_core_varlen(*args,cu_seqlens=cu_seqlens,layout=layout,gate_delta=gate_delta)')
edit('__init__.py','return _fixed_core(*args,ctas=ctas)','return _fixed_core(*args,ctas=ctas,gate_delta=gate_delta)')
edit('__init__.py','def voc_dism(*args, direction, hard, cu_seqlens=None, layout=None, ctas=0):','def voc_dism(*args, direction, hard, cu_seqlens=None, layout=None, ctas=0, gate_delta=None):')
edit('__init__.py','direction=direction,hard=hard)','direction=direction,hard=hard,gate_delta=gate_delta)')
edit('__init__.py','direction=direction,hard=hard,ctas=ctas)','direction=direction,hard=hard,ctas=ctas,gate_delta=gate_delta)')
# Version opaque compiled identities, retain v3 calls with gate=None.
edit('compiler.py',"flash_dism::voc_forward_bnhd'","flash_dism::voc_forward_bnhd_v4'")
edit('compiler.py',"flash_dism::voc_backward_bnhd'","flash_dism::voc_backward_bnhd_v4'")
edit('compiler.py','boundaries: Optional[torch.Tensor], layout: Optional[torch.Tensor] = None) -> list[torch.Tensor]:','boundaries: Optional[torch.Tensor], layout: Optional[torch.Tensor] = None,\n                gate_delta: Optional[torch.Tensor] = None) -> list[torch.Tensor]:')
edit('compiler.py','iq, ik, direction, hard, tau), layout.view','iq, ik, direction, hard, tau)+(() if gate_delta is None else (gate_delta,)), layout.view')
edit('compiler.py','def _forward_fake(q, k, sq, sk, v, eq, ek, tau, direction, hard, boundaries, layout=None):','def _forward_fake(q, k, sq, sk, v, eq, ek, tau, direction, hard, boundaries, layout=None, gate_delta=None):')
edit('compiler.py','q, k, sq, sk, v, eq, ek, tau, direction, hard = inputs','q, k, sq, sk, v, eq, ek, tau, direction, hard = inputs[:10]\n    gate_delta = inputs[10] if len(inputs)==11 else None')
edit('compiler.py','    prepared = list(cu.prepare_operands(raw, boundaries is not None, True))\n    prepared.append(boundary)','    prepared = list(cu.prepare_operands(raw+(() if gate_delta is None else (gate_delta,)), boundaries is not None, True))\n    if gate_delta is None: prepared.append(boundary)\n    else: prepared[12]=boundary')
edit('compiler.py','    return [grad.contiguous() for grad in gradients]','    if gate_delta is not None: gradients.append(g["gate_delta"])\n    return [grad.contiguous() for grad in gradients]')
edit('compiler.py','    return [t.new_empty(t.shape) for t in inputs[:8]]','    return [t.new_empty(t.shape) for t in inputs[:8]+inputs[10:]]')
edit('compiler.py','    ctx.has_layout = inputs[11] is not None','    ctx.has_layout = inputs[11] is not None\n    ctx.has_gate = inputs[12] is not None')
edit('compiler.py','*([inputs[11]] if ctx.has_layout else []))','*([inputs[11]] if ctx.has_layout else []),\n                          *([inputs[12]] if ctx.has_gate else []))')
edit('compiler.py','gradients = voc_backward(list(saved[:10]), list(saved[10:20]),','gradients = voc_backward(list(saved[:10])+([saved[-1]] if ctx.has_gate else []), list(saved[10:20]),')
edit('compiler.py','return (*gradients, None, None, None, None)[:len(ctx.needs_input_grad)]','return (*gradients[:8], None, None, None, None, gradients[8] if ctx.has_gate else None)[:len(ctx.needs_input_grad)]')
# Attention module accepts externally computed gate_delta; gate projection remains caller-owned.
edit('module.py',"('hard_prob', 'direction', 'hard', 'hard_seed', 'generator')}","('hard_prob', 'direction', 'hard', 'hard_seed', 'generator')}\n        gate_delta = kwargs.get('gate_delta')")
edit('module.py','        if torch_path:\n','        if torch_path and gate_delta is not None:\n            raise NotImplementedError("v4 gate_delta currently requires aligned CUDA execution")\n        if torch_path:\n')
edit('module.py','        output = self._forward_cuda(x, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen, **options)','''        if indices is not None and gate_delta is not None:
            gate_delta = gate_delta.transpose(1,2).reshape(-1,self.heads)[indices].T.unsqueeze(0).contiguous()
        output = self._forward_cuda(x, cu_seqlens=cu_seqlens, max_seqlen=max_seqlen, gate_delta=gate_delta, **options)''')
edit('module.py','hard_seed=None, generator=None, cu_seqlens=None, max_seqlen=None):','hard_seed=None, generator=None, cu_seqlens=None, max_seqlen=None, gate_delta=None):')
edit('module.py','cu_seqlens, compiled_layout)[0]','cu_seqlens, compiled_layout, gate_delta)[0]')
edit('module.py','direction=direction, hard=hard, layout=layout)','direction=direction, hard=hard, layout=layout, gate_delta=gate_delta)')
print('Python/autograd/compiler plumbing applied')
